name: Publish to pypi on push

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Bump the version ➕
        run: |
          next_version() {
            current_version=$(grep -oP 'version="\K(.*)(?=")' setup.py)
            major=$(echo $current_version | cut -d. -f1)
            minor=$(echo $current_version | cut -d. -f2)
            patch=$(echo $current_version | cut -d. -f3)
            echo "$major.$minor.$((patch + 1))"
          }
          sed -i "s/version=".*"/version=\"$(next_version)\",/" setup.py

      - name: Build and publish 🚀
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist
          python -m twine upload --repository pypi --skip-existing dist/*